### ISSUE TITLE
Redesign data for Rpg

### ISSUE THREAD

**Issue by czeano** [czeano/upbeat#10]
1. Create new base class like GameData for all game data classes. It will have an class attribute that all instantiated objects are added to, kind of like django's model.Model.objects.
2. Reorg all data loading to be done by the first call to gamedatatype.objects from REST (so we're not calling load() functions explicitly)

**Comment by Jurph** [comment]
At the table we draw a distinction between players and characters - does
having a 'player' (or even a 'PHB') object with pointers to the DB, in
order to handle game knowledge, make sense?

-jrp

**Comment by czeano** [comment]
RpgGameDB is essentially PHB... and in fact I might use that for the renaming in #9 . The more I fret over this, the more I'm thinking the assigning of PHB data to Characters is gonna have to be in some sort of controller God Object, which is probably terrible design.

**Comment by czeano** [comment]
OR, instead of freeforming all of this I need to adopt an existing framework that makes it easier to access models globally.

**Comment by Jurph** [comment]
God Objects are a bad idea.  Excuse possible misuse or overloading of terms
like object/class here -- no formal CS or OO background -- but I think you
want to look at something like:

Start with a static relational DB for the unchanging PHB/DMG info.  A
player puts a quarter in the slot on the front of the PHB/DMG and creates a
single dynamic object ("player-character").  This goes through all the
trees in the relational DB once -- if wizard then incorporate spell table;
if dwarf incorporate beer and beard puns; etc. Where necessary it calls out
to the dice object.

Enough PCs being present, or a player saying "let's play" triggers the
DM-bot to put several dollars in the slot on the front of the PHB/DMG and
create an encounter, which has:

- One setting (which may determine theme, which may limit monster choice,
or which may just be flavor text - this object should start as a stub)
- NPCs (almost always monsters, esp. in beginning trivial cases)
- set dressing (special sub-class of NPC that lets PCs leverage skills like
"hide" or reacts to certain abilities like fireball by 'exploding',
probably an 'attack')
- an initiative table with slots for every PC and NPC
- copies of all of the participating PCs, which will have their dynamic
stats (hit points, XP) decremented and incremented throughout

The players can read from the PHB while building characters, or through a
'help' function.  The encounter can create a static copy of a subset of the
PHB (based on which players & monsters are present) or just have read
access to the whole thing for adjudicating actions.

**Comment by czeano** [comment]
keanu-reeves-whoa.jpg

**Comment by Jurph** [comment]
BuildEncounter()
- GetSetting from Settings (dice, settings tables)
 -- GetSetDressing eventually
 -- GetOptionalRuleMods (fire spells do double damage, races other than
dwarves begin to suffocate from mine gas in 5 rounds, etc.)
- GetCharacters from Tavern / World
- GetMonsters (optionally use number & toughness of characters, and/or
details from setting to do this part)
- Roll Initiative()

RunEncounter()
 - NextInitiative
 - GetInput (calls either PC or NPC routine)
  -- PC routine (timer, dice, keyboard input)
  -- NPC routine (monster AI, dice, timer)
 - AdjudicateActions (dice, PHB/DMG)
 - NextRound (check for overwhelming odds, check for per-round conditions)

Also this is going to be a pain-in-the-ass dealing with "character" in any
kind of scripting language because you're going to run into parsers that
think you mean a char or CHAR() or byte or whatever...  might want to use
Toon() or somesuch.

...I'm really supposed to be studying but I think you see where I'm going.

**Comment by czeano** [comment]
I'm gonna delete this ticket just so I stop distracting you. :)

**Comment by czeano** [comment]
(side note: The reserved word that keeps punching me in the face isn't so much Character as Class, and typing out CharacterClass every time is annoying. Might get renamed to archetype or job REAL SOON NOW.)
